repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        additional_dependencies:
          - types-setuptools
          - litellm>=1.51.0
          - numpy>=1.25.0
          - pandas>=2.0.0
          - sentence-transformers>=3.0.1
          - tiktoken>=0.7.0
          - tqdm>=4.66.4
