import pandas as pd

import lotus
from lotus.models import LM

gpt_35_turbo = LM("gpt-3.5-turbo")
gpt_4o = LM("gpt-4o")

lotus.settings.configure(lm=gpt_4o, helper_lm=gpt_35_turbo)
data = {
    "Course Name": [
        "Probability and Random Processes",
        "Optimization Methods in Engineering",
        "Digital Design and Integrated Circuits",
        "Computer Security",
        "Data Structures and Algorithms",
        "Machine Learning",
        "Artificial Intelligence",
        "Natural Language Processing",
        "Introduction to Robotics",
        "Control Systems",
        "Linear Algebra and Differential Equations",
        "Database Systems",
        "Cloud Computing",
        "Software Engineering",
        "Operating Systems",
        "Discrete Mathematics",
        "Numerical Methods",
        "Wireless Communication Systems",
        "Embedded Systems",
        "Advanced Computer Architecture",
        "Graph Theory",
        "Cryptography and Network Security",
        "Big Data Analytics",
        "Deep Learning",
        "Organic Chemistry",
        "Molecular Biology",
        "Environmental Science",
        "Genetics and Evolution",
        "Human Physiology",
        "Introduction to Anthropology",
        "Cultural Studies",
        "Political Theory",
        "Macroeconomics",
        "Microeconomics",
        "Introduction to Sociology",
        "Developmental Psychology",
        "Cognitive Science",
        "Introduction to Philosophy",
        "Ethics and Moral Philosophy",
        "History of Western Civilization",
        "Art History: Renaissance to Modern",
        "World Literature",
        "Introduction to Journalism",
        "Public Speaking and Communication",
        "Creative Writing",
        "Music Theory",
        "Introduction to Theater",
        "Film Studies",
        "Environmental Policy and Law",
        "Sustainability and Renewable Energy",
        "Urban Planning and Design",
        "International Relations",
        "Marketing Principles",
        "Organizational Behavior",
        "Financial Accounting",
        "Corporate Finance",
        "Business Law",
        "Supply Chain Management",
        "Operations Research",
        "Entrepreneurship and Innovation",
        "Introduction to Psychology",
        "Health Economics",
        "Biostatistics",
        "Social Work Practice",
        "Public Health Policy",
        "Environmental Ethics",
        "History of Political Thought",
        "Quantitative Research Methods",
        "Comparative Politics",
        "Urban Economics",
        "Behavioral Economics",
        "Sociology of Education",
        "Social Psychology",
        "Gender Studies",
        "Media and Communication Studies",
        "Advertising and Brand Strategy",
        "Sports Management",
        "Introduction to Archaeology",
        "Ecology and Conservation Biology",
        "Marine Biology",
        "Geology and Earth Science",
        "Astronomy and Astrophysics",
        "Introduction to Meteorology",
        "Introduction to Oceanography",
        "Quantum Physics",
        "Thermodynamics",
        "Fluid Mechanics",
        "Solid State Physics",
        "Classical Mechanics",
        "Introduction to Civil Engineering",
        "Material Science and Engineering",
        "Structural Engineering",
        "Environmental Engineering",
        "Energy Systems Engineering",
        "Aerodynamics",
        "Heat Transfer",
        "Renewable Energy Systems",
        "Transportation Engineering",
        "Water Resources Management",
        "Principles of Accounting",
        "Project Management",
        "International Business",
        "Business Analytics",
    ]
}
df = pd.DataFrame(data)
user_instruction = "{Course Name} requires a lot of math"
df, stats = df.sem_filter(
    user_instruction=user_instruction,
    learn_cascade_threshold_sample_percentage=0.5,
    recall_target=0.9,
    precision_target=0.9,
    failure_probability=0.2,
    return_stats=True,
)
print(df)
print(stats)
