import pandas as pd

import lotus
from lotus.models import LM, SentenceTransformersRM

lm = LM(model="gpt-4o-mini")
rm = SentenceTransformersRM(model="intfloat/e5-base-v2")

lotus.settings.configure(lm=lm, rm=rm)
data = {
    "Course Name": [
        "Probability and Random Processes",
        "Optimization Methods in Engineering",
        "Digital Design and Integrated Circuits",
        "Data Structures and Algorithms",
        "Artificial Intelligence",
        "Natural Language Processing",
        "Introduction to Robotics",
        "Linear Algebra and Differential Equations",
        "Database Systems",
        "Cloud Computing",
        "Software Engineering",
        "Operating Systems",
        "Discrete Mathematics",
        "Wireless Communication Systems",
        "Embedded Systems",
        "Advanced Computer Architecture",
        "Cryptography and Network Security",
        "Big Data Analytics",
        "Environmental Studies",
        "Genetics and Evolution",
        "Human Physiology",
        "Introduction to Anthropology",
        "Macroeconomics",
        "Microeconomics",
        "Introduction to Sociology",
        "Developmental Psychology",
        "Cognitive Science",
        "Introduction to Philosophy",
        "Ethics and Moral Philosophy",
        "History of Western Civilization",
        "Art History: Renaissance to Modern",
        "World Literature",
        "Introduction to Journalism",
        "Public Speaking and Communication",
        "Creative Writing",
        "Introduction to Theater",
        "Film Studies",
        "Environmental Policy and Law",
        "Sustainability and Renewable Energy",
        "Urban Planning and Design",
        "International Relations",
        "Marketing Principles",
        "Organizational Behavior",
        "Financial Accounting",
        "Corporate Finance",
        "Operations Research",
        "Entrepreneurship and Innovation",
        "Introduction to Psychology",
        "Biostatistics",
        "Social Work Practice",
        "Public Health Policy",
        "Environmental Ethics",
        "History of Political Thought",
        "Quantitative Research Methods",
        "Comparative Politics",
        "Behavioral Economics",
        "Sociology of Education",
        "Social Psychology",
        "Gender Studies",
        "Media and Communication Studies",
        "Advertising and Brand Strategy",
        "Sports Management",
        "Introduction to Archaeology",
        "Ecology and Conservation Biology",
        "Geology and Earth Science",
        "Astronomy and Astrophysics",
        "Introduction to Meteorology",
        "Introduction to Oceanography",
        "Introduction to Civil Engineering",
        "Material Science and Engineering",
        "Structural Engineering",
        "Environmental Engineering",
        "Energy Systems Engineering",
        "Aerodynamics",
        "Renewable Energy Systems",
        "Transportation Engineering",
        "Water Resources Management",
        "Principles of Accounting",
        "Project Management",
        "International Business",
        "Business Analytics",
    ]
}

skills = [
    "Math", "Computer Science", "Management", "Writing", "Data Analysis", "Machine Learning", "Project Management",
    "Communication", "Problem Solving", "Creativity", "Critical Thinking", "Public Speaking", "Teamwork",
    "Adaptability", "Programming", "Leadership", "Time Management", "Negotiation", "Decision Making", "Networking",
    "Presentation", "Customer Service", "Marketing", "Graphic Design", "Research", "SEO", "Content Creation",
    "Video Editing", "Sales", "Financial Analysis", "Accounting", "Event Planning", "Foreign Languages",
    "Software Development", "Cybersecurity", "Social Media Management", "Photography", "Writing & Editing",
    "Technical Support", "Database Management", "Web Development", "Business Strategy", "Operations Management",
    "UI/UX Design", "Machine Learning", "Data Visualization", "Product Management", "Cloud Computing",
    "Agile Methodology", "Blockchain", "IT Support", "Legal Research", "Supply Chain Management", "Copywriting",
    "Human Resources", "Quality Assurance", "Medical Research", "Healthcare Management", "Sports Coaching",
    "Editing & Proofreading", "Legal Writing", "Human Anatomy", "Chemistry", "Physics", "Biology", "Psychology",
    "Sociology", "Anthropology", "Political Science", "Public Relations", "Fashion Design", "Interior Design",
    "Automotive Repair", "Plumbing", "Carpentry", "Electrical Work", "Welding", "Electronics", "Hardware Engineering",
    "Circuit Design", "Robotics", "Environmental Science", "Marine Biology", "Urban Planning", "Geography",
    "Agricultural Science", "Animal Care", "Veterinary Science", "Zoology", "Ecology", "Botany", "Landscape Design",
    "Baking & Pastry", "Culinary Arts", "Bartending", "Nutrition", "Dietary Planning", "Physical Training", "Yoga",
    "Meditation", "Dance", "Music Production", "Audio Engineering", "Voice Acting", "Acting", "Film Production",
    "Directing", "Screenwriting", "Set Design", "Costume Design", "Stage Management", "Sound Design", "Lighting Design",
    "History", "Art History", "Philosophy", "Religious Studies", "Economics", "Statistics", "Calculus", "Algebra",
    "Geometry", "Trigonometry", "Early Childhood Education", "Special Education", "Teaching", "Curriculum Development",
    "Educational Psychology", "Instructional Design", "Library Science", "Museum Studies", "Archaeology",
    "Content Strategy", "Branding", "Product Design", "Industrial Design", "Supply Chain Analysis", "Manufacturing",
    "Logistics", "Warehouse Management", "Inventory Management", "Risk Management", "Compliance", "Auditing",
    "Portfolio Management", "Investment Analysis", "Real Estate", "Insurance", "Claims Processing", "Underwriting",
    "Tax Preparation", "Financial Planning", "Estate Planning", "Business Analysis", "Data Mining", "Big Data",
    "Natural Language Processing", "Speech Recognition", "Machine Vision", "Bioinformatics", "Chemoinformatics",
    "Geoinformatics", "Energy Management", "Construction Management", "Property Management", "Facility Management",
    "Hotel Management", "Travel Planning", "Event Coordination", "Salesforce", "Customer Relationship Management (CRM)",
    "SAP", "Oracle", "Microsoft Excel", "Microsoft Word", "Microsoft PowerPoint", "Microsoft Outlook", "Google Sheets",
    "Google Docs", "Slack", "Trello", "JIRA", "Confluence", "Asana", "Adobe Photoshop", "Adobe Illustrator",
    "Adobe Premiere Pro", "Adobe After Effects", "CorelDRAW", "Figma", "Sketch", "Canva", "Final Cut Pro", "Unity",
    "Unreal Engine", "Game Design", "Game Development", "Simulation Modeling", "Virtual Reality", "Augmented Reality",
    "Quantum Computing", "3D Printing", "Nanotechnology"
]
data2 = pd.DataFrame({"Skill": skills})


df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data2)
join_instruction = "Taking {Course Name:left} will help me learn {Skill:right}"
res = df1.sem_join(df2, join_instruction, recall_target = 0.9, precision_target = 0.9, sampling_percentage = 0.8)
print(res)
